alias ag='apt-get'
alias v='vim'
alias vi='vim'
alias vimm='vim'
alias -g G='| grep'
alias ls='ls --color=always -lah'
alias ..='cd ..'
alias ...='cd ../..'
alias zr='source ~/.zshrc && print "zsh config has been reloaded"'
alias ssh='TERM=rxvt-unicode ssh'
alias chrome='google-chrome'
alias volume='pactl set-sink-volume 0 '
alias ashi='ash inbox'
