#!/bin/bash

pkill keynav

:profile() {
    pactl set-card-profile 0 "$1"
    pactl set-card-profile 1 "$1"
}

profile="$AUTORANDR_CURRENT_PROFILE"
if [[ "$profile" == "tv" ]]; then
    :profile "output:hdmi-stereo+input:analog-stereo"
else
    :profile "output:analog-stereo+input:analog-stereo"
fi

echo "$profile" > ~/.config/autorandr_profile

if [[ "$profile" =~ office ]]; then
    redshift stop
fi
